
spring:
  rabbitmq:
    host: 192.168.5.44
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost

    # 这里支持两种类型：simple：同步等待confirm结果，直到超时；
    # correlated：异步回调，定义ConfirmCallback，MQ返回结果时会回调这个ConfirmCallback
    publisher-confirm-type: correlated
    # publish-returns：开启publish-return功能，同样是基于callback机制，不过是定义ReturnCallback
    publisher-returns: true
    # 定义消息路由失败时的策略。true，则调用ReturnCallback；false：则直接丢弃消息
    template:
      mandatory: true
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          # 开启消费者失败重试
          enabled: true
          # 初始的失败等待时长为1秒
          initial-interval: 1000
          # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          multiplier: 2.0
          # 最大重试次数
          max-attempts: 4
          # true无状态；false有状态。如果业务中包含事务，这里改为false
          stateless: true
          max-interval: 5000
